version: '3.3'
  
services:
  app:
    build: .
 
   ports:
      - 8089:80
    restart: always

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: password
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
